stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Xmx512m"
  # Prevent Docker from pulling image if already exists
  DOCKER_PULL_POLICY: "if-not-present"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.8.6-jdk-17
  script:
    - mvn compile

test:
  stage: test
  image: maven:3.8.6-jdk-17
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml