stages:
  - build
  - test
  - deploy

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Cache dependencies between runs
cache:
  paths:
    - .m2/repository/
    - target/

# Build stage jobs



# Test stage jobs
unit-test:
  stage: test
  script:
    - echo "Running unit tests..."

integration-test:
  stage: test
  script:
    - echo "Running integration tests..."
    - echo "Integration tests completed"


# Deploy stage job
deploy-application:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master




test:
  stage: test
  image: maven:3.8.6-openjdk-17  # or gradle:8.4.0-jdk17 for Gradle
  script:
    - mvn clean test  # or 'gradle test' for Gradle
  artifacts:
    when: always
    paths:
      - target/surefire-reports/  # For test reports
    reports:
      junit: target/surefire-reports/*.xml  # For test visualization